### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by mvieth**
- Remove unnecessary semicolons
- Remove unused-parameter warning
- Make loop parameter signed to avoid signed-unsigned warning
- Fix typo

I set lunar-devel as target because that is the default-branch, but I can switch to noetic-devel if you like.

### CODE REVIEW

**Comment by jonbinney** [comment]
@mvieth thanks for this! I've retargeted this to noetic-devel and I'll merge once tests pass.

**Comment by jonbinney** [comment]
Hmm... actually it looks like the auto-retarget didn't work. @mvieth could you fix the conflicts?

**Comment by mvieth** [comment]
> Hmm... actually it looks like the auto-retarget didn't work. @mvieth could you fix the conflicts?

Those conflicts seem pretty bad. I think it would be easier (and safer) if I create a new PR that directly targets noetic-devel. Would that be okay for you @jonbinney ?

**Comment by jonbinney** [comment]
@mvieth that sounds good. Thank you!

**Comment by jonbinney** [comment]
Closing in favor of https://github.com/ros/filters/pull/58

**Pull request closed without merging**
