### PR TITLE
Make FilterBase::getName() const.

### PR DESCRIPTION
**Pull request by peci1**

### CODE REVIEW

**Review by tfoote — APPROVED** [review]
lgtm, I'm also going to manually rebase and merge into noetic.

**Comment by peci1** [comment]
Now that the noetic PR is merged, could this be merged to lunar-devel?

**Comment by peci1** [comment]
Thanks @jonbinney . Is there a melodic release planned?

**Comment by jonbinney** [comment]
@peci1 done: https://github.com/ros/rosdistro/pull/30979

**Comment by peci1** [comment]
@jonbinney Thanks!

**Pull request merged**
